new Vue({
    el:"#app",
    data:{
        datas:[
            {id:1,title:"这是第一个"},
            {id:2,title:"这是第二个"},
            {id:3,title:"这是第三个"},
        ],
        state:false,
        title:''
    },
    methods:{
        aa(){
            this.state=true;
        },
        bb(val){
            this.title=val;
            this.state=false;
        }
    }
})